/*
 * THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 * This file was generated by the dom/make_names.pl script.
 *
 * Copyright (C) 2005, 2006, 2007, 2008, 2009 Apple Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef DOM_WMLNAMES_H
#define DOM_WMLNAMES_H

#include "QualifiedName.h"

namespace WebCore {

 namespace WMLNames {

#ifndef DOM_WMLNAMES_HIDE_GLOBALS
// Namespace
extern const WTF::AtomicString wmlNamespaceURI;

// Tags
extern const WebCore::QualifiedName aTag;
extern const WebCore::QualifiedName accessTag;
extern const WebCore::QualifiedName anchorTag;
extern const WebCore::QualifiedName brTag;
extern const WebCore::QualifiedName cardTag;
extern const WebCore::QualifiedName doTag;
extern const WebCore::QualifiedName fieldsetTag;
extern const WebCore::QualifiedName goTag;
extern const WebCore::QualifiedName headTag;
extern const WebCore::QualifiedName imgTag;
extern const WebCore::QualifiedName inputTag;
extern const WebCore::QualifiedName insertedLegendTag;
extern const WebCore::QualifiedName metaTag;
extern const WebCore::QualifiedName noopTag;
extern const WebCore::QualifiedName oneventTag;
extern const WebCore::QualifiedName optgroupTag;
extern const WebCore::QualifiedName optionTag;
extern const WebCore::QualifiedName pTag;
extern const WebCore::QualifiedName postfieldTag;
extern const WebCore::QualifiedName prevTag;
extern const WebCore::QualifiedName refreshTag;
extern const WebCore::QualifiedName selectTag;
extern const WebCore::QualifiedName setvarTag;
extern const WebCore::QualifiedName tableTag;
extern const WebCore::QualifiedName tdTag;
extern const WebCore::QualifiedName templateTag;
extern const WebCore::QualifiedName timerTag;
extern const WebCore::QualifiedName trTag;
// Attributes
extern const WebCore::QualifiedName cache_controlAttr;
extern const WebCore::QualifiedName columnsAttr;
extern const WebCore::QualifiedName domainAttr;
extern const WebCore::QualifiedName emptyokAttr;
extern const WebCore::QualifiedName formatAttr;
extern const WebCore::QualifiedName foruaAttr;
extern const WebCore::QualifiedName inameAttr;
extern const WebCore::QualifiedName ivalueAttr;
extern const WebCore::QualifiedName localsrcAttr;
extern const WebCore::QualifiedName modeAttr;
extern const WebCore::QualifiedName newcontextAttr;
extern const WebCore::QualifiedName onenterbackwardAttr;
extern const WebCore::QualifiedName onenterforwardAttr;
extern const WebCore::QualifiedName onpickAttr;
extern const WebCore::QualifiedName ontimerAttr;
extern const WebCore::QualifiedName optionalAttr;
extern const WebCore::QualifiedName orderedAttr;
extern const WebCore::QualifiedName pathAttr;
extern const WebCore::QualifiedName sendrefererAttr;
#endif

WebCore::QualifiedName** getWMLTags(size_t* size);
WebCore::QualifiedName** getWMLAttrs(size_t* size);

void init();

} }

#endif

