#ifndef MDCONFIG_H
#define MDCONFIG_H

#define MDOLPHIN_MAJOR_VERSION              @MDOLPHIN_MAJOR_VERSION@
#define MDOLPHIN_MICRO_VERSION              @MDOLPHIN_MICRO_VERSION@
#define MDOLPHIN_MINOR_VERSION              @MDOLPHIN_MINOR_VERSION@

#define WEBKIT_MAJOR_VERSION                @WEBKIT_MAJOR_VERSION@
#define WEBKIT_MICRO_VERSION                @WEBKIT_MICRO_VERSION@
#define WEBKIT_MINOR_VERSION                @WEBKIT_MINOR_VERSION@

#define ENABLE_BACKWARD_API                 @ENABLE_BACKWARD_API_VALUE@
#define ENABLE_BLOB                         @ENABLE_BLOB_VALUE@
#define ENABLE_CAIRO_MG                     @ENABLE_CAIRO_MG_VALUE@
#define ENABLE_CAIRO_TEXT                   @ENABLE_CAIRO_TEXT_VALUE@
#define ENABLE_CANVAS                       @ENABLE_CANVAS_VALUE@
#define ENABLE_CHANNEL_MESSAGING            @ENABLE_CHANNEL_MESSAGING_VALUE@
#define ENABLE_CLIENT_BASED_GEOLOCATION     @ENABLE_CLIENT_BASED_GEOLOCATION_VALUE@
#define ENABLE_CONTEXT_MENUS                @ENABLE_CONTEXT_MENUS_VALUE@
#define ENABLE_COOKIE                       @ENABLE_COOKIE_VALUE@
#define ENABLE_DATABASE                     @ENABLE_DATABASE_VALUE@
#define ENABLE_DATALIST                     @ENABLE_DATALIST_VALUE@
#define ENABLE_DIRECTORY_UPLOAD             @ENABLE_DIRECTORY_UPLOAD_VALUE@
#define ENABLE_DISK_CACHE                   @ENABLE_DISK_CACHE_VALUE@
#define ENABLE_EVENTSOURCE                  @ENABLE_EVENTSOURCE_VALUE@
#define ENABLE_FAST_MALLOC                  @ENABLE_FAST_MALLOC_VALUE@
#define ENABLE_FAST_MOBILE_SCROLLING        @ENABLE_FAST_MOBILE_SCROLLING_VALUE@
#define ENABLE_FASTMODE                     @ENABLE_FASTMODE_VALUE@
#define ENABLE_FILE_SYSTEM                  @ENABLE_FILE_SYSTEM_VALUE@
#define ENABLE_FILECOOKIE                   @ENABLE_FILECOOKIE_VALUE@
#define ENABLE_FILESYSTEM                   @ENABLE_FILESYSTEM_VALUE@
#define ENABLE_FLOATING_PATCH               @ENABLE_FLOATING_PATCH_VALUE@
#define ENABLE_FOCUSRING_TV                 @ENABLE_FOCUSRING_TV_VALUE@
#define ENABLE_FILTERS                      @ENABLE_FILTERS_VALUE@
#define ENABLE_FTPDIR                       @ENABLE_FTPDIR_VALUE@
#define ENABLE_GEOLOCATION                  @ENABLE_GEOLOCATION_VALUE@
#define ENABLE_HIGHQUALITYZOOM              @ENABLE_HIGHQUALITYZOOM_VALUE@
#define ENABLE_ICONDATABASE                 @ENABLE_ICONDATABASE_VALUE@
#define ENABLE_INPUT_SPEECH                 @ENABLE_INPUT_SPEECH_VALUE@
#define ENABLE_INSPECTOR                    @ENABLE_INSPECTOR_VALUE@
#define ENABLE_JAVASCRIPT_DEBUGGER          @ENABLE_JAVASCRIPT_DEBUGGER_VALUE@
#define ENABLE_JIT                          @ENABLE_JIT_VALUE@
#define ENABLE_JSNATIVEBINDING              @ENABLE_JSNATIVEBINDING_VALUE@
#define ENABLE_MATHML                       @ENABLE_MATHML_VALUE@
#define ENABLE_MEDIA_STATISTICS             @ENABLE_MEDIA_STATISTICS_VALUE@
#define ENABLE_METER_TAG                    @ENABLE_METER_TAG_VALUE@
#define ENABLE_NETSCAPE_PLUGIN_API          @ENABLE_NETSCAPE_PLUGIN_API_VALUE@
#define ENABLE_NO_NPTL                      @ENABLE_NO_NPTL_VALUE@
#define ENABLE_ORIENTATION_EVENTS           @ENABLE_ORIENTATION_EVENTS_VALUE@
#define ENABLE_PLUGIN                       @ENABLE_PLUGIN_VALUE@
#define ENABLE_PROGRESS_TAG                 @ENABLE_PROGRESS_TAG_VALUE@
#define ENABLE_SCHEMEEXTENSION              @ENABLE_SCHEMEEXTENSION_VALUE@
#define ENABLE_SHARED_WORKERS               @ENABLE_SHARED_WORKERS_VALUE@
#define ENABLE_SPIDER                       @ENABLE_SPIDER_VALUE@
#define ENABLE_SSL                          @ENABLE_SSL_VALUE@
#define ENABLE_SSLFILE                      @ENABLE_SSLFILE_VALUE@
#define ENABLE_SVG                          @ENABLE_SVG_VALUE@
#define ENABLE_SVG_ANIMATION                @ENABLE_SVG_ANIMATION_VALUE@
#define ENABLE_SVG_AS_IMAGE                 @ENABLE_SVG_AS_IMAGE_VALUE@
#define ENABLE_SVG_FONTS                    @ENABLE_SVG_FONTS_VALUE@
#define ENABLE_SVG_FOREIGN_OBJECT           @ENABLE_SVG_FOREIGN_OBJECT_VALUE@
#define ENABLE_SVG_USE                      @ENABLE_SVG_USE_VALUE@
#define ENABLE_TOOLS                        @ENABLE_TOOLS_VALUE@
#define ENABLE_VIDEO                        @ENABLE_VIDEO_VALUE@
#define ENABLE_VIEWSOURCE                   @ENABLE_VIEWSOURCE_VALUE@
#define ENABLE_WCSS                         @ENABLE_WCSS_VALUE@
#define ENABLE_WEB_SOCKETS                  @ENABLE_WEB_SOCKETS_VALUE@
#define ENABLE_WML                          @ENABLE_WML_VALUE@
#define ENABLE_WORKERS                      @ENABLE_WORKERS_VALUE@
#define ENABLE_XHTMLMP                      @ENABLE_XHTMLMP_VALUE@
#define ENABLE_XPATH                        @ENABLE_XPATH_VALUE@
#define ENABLE_XSLT                         @ENABLE_XSLT_VALUE@

#cmakedefine ENABLE_FORCE_DOUBLE_ALIGN           1
#cmakedefine NDEBUG                              1

#endif /* MDCONFIG_H */
